/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppCompetitorsRouteImport } from './routes/app/competitors'
import { Route as AppExperimentsRouteImport } from './routes/app/experiments'
import { Route as AppIntentsRouteImport } from './routes/app/intents'
import { Route as AppIssuesRouteImport } from './routes/app/issues'
import { Route as AppMethodologyRouteImport } from './routes/app/methodology'
import { Route as AppProductsRouteImport } from './routes/app/products'
import { Route as AppReportsRouteImport } from './routes/app/reports'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AuditAuditIdRouteImport } from './routes/audit.$auditId'
import { Route as RReportIdRouteImport } from './routes/r.$reportId'
import { Route as AppCompetitorsIndexRouteImport } from './routes/app/competitors.index'
import { Route as AppCompetitorsBrandIdRouteImport } from './routes/app/competitors.$brandId'
import { Route as AppExperimentsIndexRouteImport } from './routes/app/experiments.index'
import { Route as AppExperimentsExperimentIdRouteImport } from './routes/app/experiments.$experimentId'
import { Route as AppIntentsIndexRouteImport } from './routes/app/intents.index'
import { Route as AppIntentsIntentIdRouteImport } from './routes/app/intents.$intentId'
import { Route as AppIssuesIndexRouteImport } from './routes/app/issues.index'
import { Route as AppIssuesIssueIdRouteImport } from './routes/app/issues.$issueId'
import { Route as AppProductsIndexRouteImport } from './routes/app/products.index'
import { Route as AppProductsProductIdRouteImport } from './routes/app/products.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCompetitorsRoute = AppCompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => AppRoute,
} as any)
const AppExperimentsRoute = AppExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => AppRoute,
} as any)
const AppIntentsRoute = AppIntentsRouteImport.update({
  id: '/intents',
  path: '/intents',
  getParentRoute: () => AppRoute,
} as any)
const AppIssuesRoute = AppIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => AppRoute,
} as any)
const AppMethodologyRoute = AppMethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AuditAuditIdRoute = AuditAuditIdRouteImport.update({
  id: '/audit/$auditId',
  path: '/audit/$auditId',
  getParentRoute: () => rootRouteImport,
} as any)
const RReportIdRoute = RReportIdRouteImport.update({
  id: '/r/$reportId',
  path: '/r/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCompetitorsIndexRoute = AppCompetitorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCompetitorsRoute,
} as any)
const AppCompetitorsBrandIdRoute = AppCompetitorsBrandIdRouteImport.update({
  id: '/$brandId',
  path: '/$brandId',
  getParentRoute: () => AppCompetitorsRoute,
} as any)
const AppExperimentsIndexRoute = AppExperimentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppExperimentsRoute,
} as any)
const AppExperimentsExperimentIdRoute =
  AppExperimentsExperimentIdRouteImport.update({
    id: '/$experimentId',
    path: '/$experimentId',
    getParentRoute: () => AppExperimentsRoute,
  } as any)
const AppIntentsIndexRoute = AppIntentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppIntentsRoute,
} as any)
const AppIntentsIntentIdRoute = AppIntentsIntentIdRouteImport.update({
  id: '/$intentId',
  path: '/$intentId',
  getParentRoute: () => AppIntentsRoute,
} as any)
const AppIssuesIndexRoute = AppIssuesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppIssuesRoute,
} as any)
const AppIssuesIssueIdRoute = AppIssuesIssueIdRouteImport.update({
  id: '/$issueId',
  path: '/$issueId',
  getParentRoute: () => AppIssuesRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProductsRoute,
} as any)
const AppProductsProductIdRoute = AppProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => AppProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/competitors': typeof AppCompetitorsRouteWithChildren
  '/app/experiments': typeof AppExperimentsRouteWithChildren
  '/app/intents': typeof AppIntentsRouteWithChildren
  '/app/issues': typeof AppIssuesRouteWithChildren
  '/app/methodology': typeof AppMethodologyRoute
  '/app/products': typeof AppProductsRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/audit/$auditId': typeof AuditAuditIdRoute
  '/r/$reportId': typeof RReportIdRoute
  '/app/': typeof AppIndexRoute
  '/app/competitors/$brandId': typeof AppCompetitorsBrandIdRoute
  '/app/experiments/$experimentId': typeof AppExperimentsExperimentIdRoute
  '/app/intents/$intentId': typeof AppIntentsIntentIdRoute
  '/app/issues/$issueId': typeof AppIssuesIssueIdRoute
  '/app/products/$productId': typeof AppProductsProductIdRoute
  '/app/competitors/': typeof AppCompetitorsIndexRoute
  '/app/experiments/': typeof AppExperimentsIndexRoute
  '/app/intents/': typeof AppIntentsIndexRoute
  '/app/issues/': typeof AppIssuesIndexRoute
  '/app/products/': typeof AppProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/methodology': typeof AppMethodologyRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/audit/$auditId': typeof AuditAuditIdRoute
  '/r/$reportId': typeof RReportIdRoute
  '/app': typeof AppIndexRoute
  '/app/competitors/$brandId': typeof AppCompetitorsBrandIdRoute
  '/app/experiments/$experimentId': typeof AppExperimentsExperimentIdRoute
  '/app/intents/$intentId': typeof AppIntentsIntentIdRoute
  '/app/issues/$issueId': typeof AppIssuesIssueIdRoute
  '/app/products/$productId': typeof AppProductsProductIdRoute
  '/app/competitors': typeof AppCompetitorsIndexRoute
  '/app/experiments': typeof AppExperimentsIndexRoute
  '/app/intents': typeof AppIntentsIndexRoute
  '/app/issues': typeof AppIssuesIndexRoute
  '/app/products': typeof AppProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/competitors': typeof AppCompetitorsRouteWithChildren
  '/app/experiments': typeof AppExperimentsRouteWithChildren
  '/app/intents': typeof AppIntentsRouteWithChildren
  '/app/issues': typeof AppIssuesRouteWithChildren
  '/app/methodology': typeof AppMethodologyRoute
  '/app/products': typeof AppProductsRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/audit/$auditId': typeof AuditAuditIdRoute
  '/r/$reportId': typeof RReportIdRoute
  '/app/': typeof AppIndexRoute
  '/app/competitors/$brandId': typeof AppCompetitorsBrandIdRoute
  '/app/experiments/$experimentId': typeof AppExperimentsExperimentIdRoute
  '/app/intents/$intentId': typeof AppIntentsIntentIdRoute
  '/app/issues/$issueId': typeof AppIssuesIssueIdRoute
  '/app/products/$productId': typeof AppProductsProductIdRoute
  '/app/competitors/': typeof AppCompetitorsIndexRoute
  '/app/experiments/': typeof AppExperimentsIndexRoute
  '/app/intents/': typeof AppIntentsIndexRoute
  '/app/issues/': typeof AppIssuesIndexRoute
  '/app/products/': typeof AppProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/competitors'
    | '/app/experiments'
    | '/app/intents'
    | '/app/issues'
    | '/app/methodology'
    | '/app/products'
    | '/app/reports'
    | '/app/settings'
    | '/audit/$auditId'
    | '/r/$reportId'
    | '/app/'
    | '/app/competitors/$brandId'
    | '/app/experiments/$experimentId'
    | '/app/intents/$intentId'
    | '/app/issues/$issueId'
    | '/app/products/$productId'
    | '/app/competitors/'
    | '/app/experiments/'
    | '/app/intents/'
    | '/app/issues/'
    | '/app/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/methodology'
    | '/app/reports'
    | '/app/settings'
    | '/audit/$auditId'
    | '/r/$reportId'
    | '/app'
    | '/app/competitors/$brandId'
    | '/app/experiments/$experimentId'
    | '/app/intents/$intentId'
    | '/app/issues/$issueId'
    | '/app/products/$productId'
    | '/app/competitors'
    | '/app/experiments'
    | '/app/intents'
    | '/app/issues'
    | '/app/products'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/competitors'
    | '/app/experiments'
    | '/app/intents'
    | '/app/issues'
    | '/app/methodology'
    | '/app/products'
    | '/app/reports'
    | '/app/settings'
    | '/audit/$auditId'
    | '/r/$reportId'
    | '/app/'
    | '/app/competitors/$brandId'
    | '/app/experiments/$experimentId'
    | '/app/intents/$intentId'
    | '/app/issues/$issueId'
    | '/app/products/$productId'
    | '/app/competitors/'
    | '/app/experiments/'
    | '/app/intents/'
    | '/app/issues/'
    | '/app/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuditAuditIdRoute: typeof AuditAuditIdRoute
  RReportIdRoute: typeof RReportIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/competitors': {
      id: '/app/competitors'
      path: '/competitors'
      fullPath: '/app/competitors'
      preLoaderRoute: typeof AppCompetitorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/experiments': {
      id: '/app/experiments'
      path: '/experiments'
      fullPath: '/app/experiments'
      preLoaderRoute: typeof AppExperimentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/intents': {
      id: '/app/intents'
      path: '/intents'
      fullPath: '/app/intents'
      preLoaderRoute: typeof AppIntentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/issues': {
      id: '/app/issues'
      path: '/issues'
      fullPath: '/app/issues'
      preLoaderRoute: typeof AppIssuesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/methodology': {
      id: '/app/methodology'
      path: '/methodology'
      fullPath: '/app/methodology'
      preLoaderRoute: typeof AppMethodologyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products': {
      id: '/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/audit/$auditId': {
      id: '/audit/$auditId'
      path: '/audit/$auditId'
      fullPath: '/audit/$auditId'
      preLoaderRoute: typeof AuditAuditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$reportId': {
      id: '/r/$reportId'
      path: '/r/$reportId'
      fullPath: '/r/$reportId'
      preLoaderRoute: typeof RReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/competitors/': {
      id: '/app/competitors/'
      path: '/'
      fullPath: '/app/competitors/'
      preLoaderRoute: typeof AppCompetitorsIndexRouteImport
      parentRoute: typeof AppCompetitorsRoute
    }
    '/app/competitors/$brandId': {
      id: '/app/competitors/$brandId'
      path: '/$brandId'
      fullPath: '/app/competitors/$brandId'
      preLoaderRoute: typeof AppCompetitorsBrandIdRouteImport
      parentRoute: typeof AppCompetitorsRoute
    }
    '/app/experiments/': {
      id: '/app/experiments/'
      path: '/'
      fullPath: '/app/experiments/'
      preLoaderRoute: typeof AppExperimentsIndexRouteImport
      parentRoute: typeof AppExperimentsRoute
    }
    '/app/experiments/$experimentId': {
      id: '/app/experiments/$experimentId'
      path: '/$experimentId'
      fullPath: '/app/experiments/$experimentId'
      preLoaderRoute: typeof AppExperimentsExperimentIdRouteImport
      parentRoute: typeof AppExperimentsRoute
    }
    '/app/intents/': {
      id: '/app/intents/'
      path: '/'
      fullPath: '/app/intents/'
      preLoaderRoute: typeof AppIntentsIndexRouteImport
      parentRoute: typeof AppIntentsRoute
    }
    '/app/intents/$intentId': {
      id: '/app/intents/$intentId'
      path: '/$intentId'
      fullPath: '/app/intents/$intentId'
      preLoaderRoute: typeof AppIntentsIntentIdRouteImport
      parentRoute: typeof AppIntentsRoute
    }
    '/app/issues/': {
      id: '/app/issues/'
      path: '/'
      fullPath: '/app/issues/'
      preLoaderRoute: typeof AppIssuesIndexRouteImport
      parentRoute: typeof AppIssuesRoute
    }
    '/app/issues/$issueId': {
      id: '/app/issues/$issueId'
      path: '/$issueId'
      fullPath: '/app/issues/$issueId'
      preLoaderRoute: typeof AppIssuesIssueIdRouteImport
      parentRoute: typeof AppIssuesRoute
    }
    '/app/products/': {
      id: '/app/products/'
      path: '/'
      fullPath: '/app/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppProductsRoute
    }
    '/app/products/$productId': {
      id: '/app/products/$productId'
      path: '/$productId'
      fullPath: '/app/products/$productId'
      preLoaderRoute: typeof AppProductsProductIdRouteImport
      parentRoute: typeof AppProductsRoute
    }
  }
}

interface AppCompetitorsRouteChildren {
  AppCompetitorsBrandIdRoute: typeof AppCompetitorsBrandIdRoute
  AppCompetitorsIndexRoute: typeof AppCompetitorsIndexRoute
}

const AppCompetitorsRouteChildren: AppCompetitorsRouteChildren = {
  AppCompetitorsBrandIdRoute: AppCompetitorsBrandIdRoute,
  AppCompetitorsIndexRoute: AppCompetitorsIndexRoute,
}

const AppCompetitorsRouteWithChildren = AppCompetitorsRoute._addFileChildren(
  AppCompetitorsRouteChildren,
)

interface AppExperimentsRouteChildren {
  AppExperimentsExperimentIdRoute: typeof AppExperimentsExperimentIdRoute
  AppExperimentsIndexRoute: typeof AppExperimentsIndexRoute
}

const AppExperimentsRouteChildren: AppExperimentsRouteChildren = {
  AppExperimentsExperimentIdRoute: AppExperimentsExperimentIdRoute,
  AppExperimentsIndexRoute: AppExperimentsIndexRoute,
}

const AppExperimentsRouteWithChildren = AppExperimentsRoute._addFileChildren(
  AppExperimentsRouteChildren,
)

interface AppIntentsRouteChildren {
  AppIntentsIntentIdRoute: typeof AppIntentsIntentIdRoute
  AppIntentsIndexRoute: typeof AppIntentsIndexRoute
}

const AppIntentsRouteChildren: AppIntentsRouteChildren = {
  AppIntentsIntentIdRoute: AppIntentsIntentIdRoute,
  AppIntentsIndexRoute: AppIntentsIndexRoute,
}

const AppIntentsRouteWithChildren = AppIntentsRoute._addFileChildren(
  AppIntentsRouteChildren,
)

interface AppIssuesRouteChildren {
  AppIssuesIssueIdRoute: typeof AppIssuesIssueIdRoute
  AppIssuesIndexRoute: typeof AppIssuesIndexRoute
}

const AppIssuesRouteChildren: AppIssuesRouteChildren = {
  AppIssuesIssueIdRoute: AppIssuesIssueIdRoute,
  AppIssuesIndexRoute: AppIssuesIndexRoute,
}

const AppIssuesRouteWithChildren = AppIssuesRoute._addFileChildren(
  AppIssuesRouteChildren,
)

interface AppProductsRouteChildren {
  AppProductsProductIdRoute: typeof AppProductsProductIdRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
}

const AppProductsRouteChildren: AppProductsRouteChildren = {
  AppProductsProductIdRoute: AppProductsProductIdRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
}

const AppProductsRouteWithChildren = AppProductsRoute._addFileChildren(
  AppProductsRouteChildren,
)

interface AppRouteChildren {
  AppCompetitorsRoute: typeof AppCompetitorsRouteWithChildren
  AppExperimentsRoute: typeof AppExperimentsRouteWithChildren
  AppIntentsRoute: typeof AppIntentsRouteWithChildren
  AppIssuesRoute: typeof AppIssuesRouteWithChildren
  AppMethodologyRoute: typeof AppMethodologyRoute
  AppProductsRoute: typeof AppProductsRouteWithChildren
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCompetitorsRoute: AppCompetitorsRouteWithChildren,
  AppExperimentsRoute: AppExperimentsRouteWithChildren,
  AppIntentsRoute: AppIntentsRouteWithChildren,
  AppIssuesRoute: AppIssuesRouteWithChildren,
  AppMethodologyRoute: AppMethodologyRoute,
  AppProductsRoute: AppProductsRouteWithChildren,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuditAuditIdRoute: AuditAuditIdRoute,
  RReportIdRoute: RReportIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
